server:
  port: 3003

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:mysql://mysql:3306/parking
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

garage:
  simulator:
    url: http://localhost:3000
